### ISSUE TITLE
[Feature]: option to place custom config in any dir, not only $homedir related

### ISSUE THREAD

**Issue by sundbing** [SolaceLabs/solace-tryme-cli#24]
### Feature Description

Make config file path adaptable and independed from $homedir of os.

currently we have to use the absolut path like ..\..\..\..\..\some\config\dir\configfile.json

### Use Case

Due to configuriation settings of company devices, we are forced to keep userprofiles clean.
next to this, we are using git for version control. 
we want to have the config files available in any directory possible, e.g. next to the executable or in any other folder.

### Proposed Solution

modify config.ts to allow given path value from outside when calling the executable,

**Comment by gvensan** [comment]
Thanks for the feedback @sundbing. Will explore this in the upcoming releases.

**Comment by gvensan** [comment]
Hi @sundbing - please download the latest release and set the environment variable STM_HOME pointing to the desired directory. All the stm related configuration & feeds will be stored in the designated directory. 

Just a note - if you start stm in a terminal where this environment variable is NOT set, it will follow the usual process of creating a default one under $HOME/.stm and proceed. So, would be a good idea to update this setting in the profile to set this on terminal launch.
